openapi: 3.0.3
info:
  title: Гаманець
  version: 0.0.1
servers:
  - url: http://localhost:8080
paths:
  /cards:
    parameters:
      - name: X-Country-Code
        in: header
        example: UA
        required: true
        schema:
          type: string
    get:
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Card"
        '500':
          description: Internal Server Error
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Card'
      responses:
        '201':
          description: Accepted
  /cards/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      - name: X-Country-Code
        in: header
        example: UA
        required: true
        schema:
          type: string
    delete:
      responses:
        '204':
          description: Accepted
    put:
      responses:
        '200':
          description: Accepted
components:
  schemas:
    Card:
      type: object
      properties:
        id:
          type:
          example: 1
          readOnly: true
        number:
          example: "4263982640269299"
          type: string
        expiration_date:
          type: string
          example: "21 січня 2023р"
        cvv:
          type: integer
          example: 222
        holder:
          type: string
          example: "Oleh"
